// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH ff AS (
    INSERT INTO feed_follows (
        id,
        user_id,
        feed_id
    )
    SELECT
        $1,          -- feed_follows.id
        u.id,        -- user_id resolved from username
        f.id         -- feed_id resolved from feed URL
    FROM users u
    JOIN feeds f
        ON f.url = $3
    WHERE u.name = $2
    ON CONFLICT (user_id, feed_id)
    DO UPDATE SET user_id = EXCLUDED.user_id
    RETURNING user_id, feed_id, created_at, updated_at, id
)
SELECT
    ff.user_id, ff.feed_id, ff.created_at, ff.updated_at, ff.id,
    u.name AS user_name,
    f.name AS feed_name
FROM ff
JOIN users u
    ON u.id = ff.user_id
JOIN feeds f
    ON f.id = ff.feed_id
`

type CreateFeedFollowParams struct {
	ID   uuid.UUID
	Name string
	Url  string
}

type CreateFeedFollowRow struct {
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ID        uuid.UUID
	UserName  string
	FeedName  string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow, arg.ID, arg.Name, arg.Url)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID,
		&i.UserName,
		&i.FeedName,
	)
	return i, err
}

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
SELECT f.name
FROM feed_follows ff
INNER JOIN users u
    ON u.id = ff.user_id
INNER JOIN feeds f
    ON f.id = ff.feed_id
WHERE u.name = $1
ORDER BY ff.updated_at DESC
`

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowFeed = `-- name: UnfollowFeed :exec
DELETE FROM feed_follows ff 
USING users u, feeds f 
WHERE ff.user_id = u.id
AND ff.feed_id = f.id
AND u.name = $1 AND f.url = $2
`

type UnfollowFeedParams struct {
	Name string
	Url  string
}

func (q *Queries) UnfollowFeed(ctx context.Context, arg UnfollowFeedParams) error {
	_, err := q.db.ExecContext(ctx, unfollowFeed, arg.Name, arg.Url)
	return err
}
